### ISSUE TITLE
Unable to Change Weapon Family

### ISSUE THREAD

**Issue by luminousgrue** [moo-man/DarkHeresy2E-FoundryVTT#54]
Weapon Family drop-down menu defaults to Las for all instances of compendium and character sheet gear. Attempting to choose a different entry from the list instantly reverts to Las.

**Comment by Akeboshiwind** [comment]
This will be fixed when #52 is merged

**Comment by luminousgrue** [comment]
> This will be fixed when #52 is merged

Do you have any idea when that might happen?

**Comment by Akeboshiwind** [comment]
It's already merged into master although it hasn't been released yet I don't think.

I do wish the repo author would mark issues as "Closed" when the relevant fix has been merged though 🤔

**Comment by moo-man** [comment]
I mark them closed when they're released, and I plan on releasing 0.8 support today, which includes the fix

**Comment by Akeboshiwind** [comment]
Ah ok, fair enough 😁

**Comment by moo-man** [comment]
Well I guess I misspoke, release is the wrong word here, the 0.8 compatible version is available for testing via this manifest link https://raw.githubusercontent.com/moo-man/DarkHeresy2E-FoundryVTT/08-support/system.json

I don't want to give an official release until it has gone through more testing, as I suspect there will be many patches needed, but this issues should be fixed in that version.

**Comment by Akeboshiwind** [comment]
Ah, thanks for the info :)

It looks like we have different ideals about releasing which is why I made
my comment earlier.
